apiVersion: v1
kind: Pod
metadata: 
  name: sa-frontend
  labels: 
    app: sa-frontend
spec:
  containers:
    - image: alexstanfield/sa-frontend
      name: sa-frontend
      ports:
        - containerPort: 80
